### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by BabyCodr** [xuzijian629/combopt-zero#1]
I am trying to build this repository and am getting the following error when running the command make. Was wondering if you had any guidance?

combopt-zero/max-cut/lib/include/gnn_policy.h:35:19: error: use of deleted function 'torch::optim::Adam& torch::optim::Adam::operator=(torch::optim::Adam&&)'
   35 |         optimizer = torch::optim::Adam(gnn->parameters(),
      |         ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   36 |                                        torch::optim::AdamOptions(cfg::learning_rate).weight_decay(cfg::weight_decay)

**Comment by xuzijian629** [comment]
Hello, could you tell me the version of LibTorch?
As specified in readme, it must be `<= 1.3.0`. We also observed some similar errors when we use latest version.

**Comment by BabyCodr** [comment]
Thank you , that fixed it
