### ISSUE TITLE
CUDA error: invalid device ordinal (exchangeDevice at /pytorch/c10/cuda/impl/CUDAGuardImpl.h:31)

### ISSUE THREAD

**Issue by BabyCodr** [xuzijian629/combopt-zero#2]
I have managed to build the repositary however running t_sample.sh gives this error. Is this something that you have also observed. If so do know what might be causing the error?

Console Output:

[controller] 0 new data batch generated
[controller] 0 batches used for training
[updater] started
[updater] started
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: invalid device ordinal (exchangeDevice at /pytorch/c10/cuda/impl/CUDAGuardImpl.h:31)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f52767a4813 in /cs/home/mm470/Documents/Workspace/Dissertation/libtorch/lib/libc10.so)
frame #1: <unknown function> + 0xdf2d (0x7f52738adf2d in /cs/home/mm470/Documents/Workspace/Dissertation/libtorch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x41beafa (0x7f527ab87afa in /cs/home/mm470/Documents/Workspace/Dissertation/libtorch/lib/libtorch.so)
frame #3: <unknown function> + 0x3c78098 (0x7f527a641098 in /cs/home/mm470/Documents/Workspace/Dissertation/libtorch/lib/libtorch.so)

**Comment by xuzijian629** [comment]
It seems you are running the code on a GPU with invalid device number.

Our code uses 2 GPUs, by default.
https://github.com/xuzijian629/combopt-zero/blob/master/feedback-set/train_controller.py#L107 (2 model updaters are running on different gpus)

you can remove Line 108-109 so that they will only use one gpu.

Does this fix it?

**Comment by xuzijian629** [comment]
It seems you are running a code on a GPU with an invalid id

**Comment by BabyCodr** [comment]
I think that has sorted it. I now get the following error , should I decrease the batch size since I'm only using one GPU?


  what():  CUDA error: out of memory (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:241)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f8b7354e813 in /cs/home/mm470/Documents/Workspace/Dissertation/libtorch/lib/libc10.so)
frame #1: <unknown function> + 0x1cb50 (0x7f8b70666b50 in /cs/home/mm470/Documents/Workspace/Dissertation/libtorch/lib/libc10_cuda.so)
frame #2: <unknown function> + 0x1de6e (0x7f8b70667e6e in /cs/home/mm470/Documents/Workspace/Dissertation/libtorch/lib/libc10_cuda.so)

**Comment by xuzijian629** [comment]
Perhaps these generators and learners are too many.

https://github.com/xuzijian629/combopt-zero/blob/master/feedback-set/config.sh#L20

Can you reduce these parallel hyperparameters (batch sizes may also effective) and try again?

**Comment by BabyCodr** [comment]
Thank you that has prevented that error. Lastly I now get the following when I run t_sample.sh and then e_sample.sh

Running t_sample.sh

....
[generator] best model not found
[generator] generated new data
[generator] best model not found
[generator] generated new data
[generator] best model not found
[generator] generated new data
[generator] best model not found
[generator] generated new data
[generator] best model not found
[generator] generated new data
[generator] best model not found
[generator] generated new data
^Z
[7]+  Stopped                 ./t_sample.sh


(venv) mm470@pc5-036-l:~/Documents/Workspace/Dissertation/combopt-zero/vertex-cover $ ./e_sample.sh
Traceback (most recent call last):
  File "./evaluate.py", line 25, in <module>
    assert has_best(opt)
AssertionError

Does the training need to go on for longer for a best model to be generated/ is this the output you expect from t_sample.sh?

**Comment by xuzijian629** [comment]
It's specified here. By default, best model will be generated after 1 minute.

https://github.com/xuzijian629/combopt-zero/blob/master/feedback-set/config.sh#L75

**Comment by BabyCodr** [comment]
Ok thank you. I am also having trouble with t_sample.sh not generating any training samples now.

[controller] 0 new data batch generated
[controller] 0 batches used for training
[updater] started
[controller] 0 new data batch generated
[controller] 0 batches used for training
[controller] 0 new data batch generated
[controller] 0 batches used for training
[controller] 0 new data batch generated
[controller] 0 batches used for training
[controller] 0 new data batch generated
[controller] 0 batches used for training

It just repeatedly prints this. Do you have an idea as to what would cause this to happen?

**Comment by xuzijian629** [comment]
It seems [generator] and [learner] are doing some task (otherwise, they will also log).

Did you changed some other hyperparameters, such as `max_n`? If the graphs are too large, or `save_interval`, `batch_num` are too large, generators or learners will take time.

Some other possible reason: Our generators and learners run in process-parallel way. So if you are running this code in a single processor, each job will take a long time until finish. Please check your CPU usage and GPU usage.

A very good setting of hyperparameters will satisfy following conditions:
`num_parallel_generator` + `num_parallel_learner` + 2 <= num of cpus

But we observed that the default setting (at this repository, not at original paper) performs in a good way with my laptop.

**Comment by xuzijian629** [comment]
Please change hyperparameters so that CPU usage and GPU usage (you can check it by nvidia-smi) under 100% and try again

**Comment by BabyCodr** [comment]
Great thanks for the detailed reply I'll do some investigations

**Comment by xuzijian629** [comment]
Another possible reason is that your file is **locked** by a process.
https://github.com/xuzijian629/combopt-zero/blob/master/feedback-set/single_data_generator.py#L19

We are sorry that our program does not erase the lock file if it's terminated unexpectedly. Could you *rm* your results directory and run it again?

**Comment by BabyCodr** [comment]
Both tweaking the parameters and deleting the result file has resulted in the program working perfectly thank you very much for your help.
