### ISSUE TITLE
Testing giving score 0

### ISSUE THREAD

**Issue by BabyCodr** [xuzijian629/combopt-zero#3]
When training and testing the Max-cut problem on ER graphs size 60 0.15 periodic testing of the model gives 0 for the first few iterations. It is not clear to me why this is. This isn't too much of an issue for small graphs but when I test on larger graphs such as size 100 the test score continuously returns zero. Do you have an idea of why this would happen? It seems odd as this means it is simply putting all nodes into one set and none in the other

**Comment by xuzijian629** [comment]
> the model gives 0 for the first few iteration

At first, the GNN does not have good prediction. As described in the paper, MCTS choose the best action among 2n options (n is node number). The first n actions corresponds to color node v by black, and latter n actions mean coloring by white. For example, if the GNN is not well-trained and tends to output higher values for first n options, it means that it always colors selected nodes with the same color.

If you train the GNN with large graphs, it is more likely that the GNN does not perform well in the early stage of training, especially when hyperparameters are not well tuned.

**Comment by BabyCodr** [comment]
Ok thanks , are there any hyperparameters in particular that I should focus on tuning to help with this?

**Comment by xuzijian629** [comment]
The numbers of learners and data generators are important. We set them as 24 and 6, respectively, when trained for MaxCut with n <= 50 (note that the number of actions <= 100, in this case).

However, I think it is difficult to tune parameters for MaxCut when trained on graphs with n >= 100.
MCTS has k actions to explore, it rollouts c_iter * k actions for computing best action each time. In MaxCut case, it needs n steps until final state, so total number of rollout could be about 2 * c_iter * n * n.
In each rollout, there is a GNN call (unless the result is memoized) and our GNN takes O(n^2 * layer_num) for inference (we didn't implement sparse matrix multiplication).
Therefore, it actually has a heavy dependence on the number of vertices. If you want to train on graphs with more than 100 node for MaxCut, I'm sure that you need an extraordinary computing environment and computation time. If you want to accelerate our implementation, it would be most helpful to implement matrix multiplication by sparse operations.

**Comment by BabyCodr** [comment]
Ok thanks for the details. I don't have any need to train on graphs >=100 I am currently training on graphs of size 60 but am testing the generalisation performance on graphs of size 100.

**Comment by xuzijian629** [comment]
Is this issue resolved?
