### ISSUE TITLE
input issue

### ISSUE THREAD

**Issue by hmtbgc** [xuzijian629/combopt-zero#5]
hi, amazing work!
Q:when I run my own test, I met a error:"../combopt-zero/independent-set/lib/src/lib/graph.cpp:17: void Graph::add_edge(int, int): Assertion `0 <= b && b < num_nodes' failed."
But I think there is no "out of range" error. Could you help this problem?
[test.txt](https://github.com/xuzijian629/combopt-zero/files/5886893/test.txt)

**Comment by xuzijian629** [comment]
The graph seems valid.
How did you use this file?
For example, if you use this file as an input for [this function](https://github.com/xuzijian629/combopt-zero/blob/2eeb73548707a8c27a270e7854cebc605f14f545/independent-set/lib/src/lib/util.cpp#L73), since it first reads `batch_n`, it may read different `n` and `m` and causes an index out of bounds error.

**Comment by hmtbgc** [comment]
Thanks for your quick reply.
My test is for "independent set" problem.(BTW, there is a typo in "independent-set/lib/lib.py Line 10, "indenpendent----->independent"")

I put the test in directory "test_graphs" and modified the "graph_name" in shell script "e_sample.sh"
(BTW, training process is ok. So I got the correct "best" file.)

And then the program returned me a "**assert error**": 
<img width="443" alt="errot" src="https://user-images.githubusercontent.com/32740258/106228216-e0d06d80-6225-11eb-82ca-e5d7f087e636.PNG">

I did not change anything else.
Maybe I should modify something else in "e_sample.sh"?
(BTW, I have checked some other tests. They are all successful.)

**Comment by hmtbgc** [comment]
I print the "b" and "num_nodes" in "/combopt-zero/independent-set/lib/src/lib/graph.cpp" and I realized the reason.
The official code doesn't consider the node which does not appear in the input file.
For example, in my "test.txt", the number of total node is 23, but node 13 and node 21 do not appear in the file. So, program incorrectly thinks the total number is 21, which leads to a "assert error" .
Maybe the author could preprocess the input and put those "degree 0" node into answer set:)

**Comment by hmtbgc** [comment]
I fixed typo and issue #5. Now it can run successfully when it encounter the above situation
